/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import Modelo.Empresa;
import controlador.Categoria;
import controlador.Noticia;
import controlador.Usuario;
import controlfechas.Fecha;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dam
 */
public class PnAltaNoticias extends javax.swing.JPanel {

    DefaultComboBoxModel modelo;
    Empresa empresa;
    Usuario usuario;

    /**
     * Creates new form PnAltaNoticias
     */
    public PnAltaNoticias(Empresa empresa, Usuario usuario) {
        initComponents();
        this.empresa = empresa;
        modelo = new DefaultComboBoxModel();
        listaCategoria.setModel(modelo);
        this.usuario = usuario;
        txtUsuario.setText(usuario.getNombre());
        cargarCategoria();
    }

    private void cargarCategoria() {
        modelo.addElement("Seleccione un curso");
        modelo.addAll(empresa.getCategorias());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btAceptar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JLabel();
        listaCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        codNotic = new javax.swing.JTextField();

        jLabel1.setText("Titulo");

        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTituloKeyPressed(evt);
            }
        });

        jLabel2.setText("Categoría");

        jLabel3.setText("Usuario");

        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
        });

        jLabel4.setText("Fecha");

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txtUsuario.setText("**********************");

        listaCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaCategoriaKeyPressed(evt);
            }
        });

        jLabel5.setText("CodigoNoticia");

        codNotic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codNoticKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(txtFecha)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(listaCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(codNotic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAceptar)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(codNotic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAceptar)
                    .addComponent(btCancelar))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        int pos = listaCategoria.getSelectedIndex();
        String txtCod;
        int codigoNot = 0;
        String titulo;
        Fecha fecha;
        txtCod = codNotic.getText();
        try {
            codigoNot = Integer.parseInt(txtCod);
            if (empresa.buscarCodigo(codigoNot)) {
                JOptionPane.showMessageDialog(this, "El codigo ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                codNotic.setText("");
                codNotic.requestFocus();
            } else {
                titulo = txtTitulo.getText();
                if (titulo.equals("")) {
                    JOptionPane.showMessageDialog(this, "Debe de tener título", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    //Usuario se pasa desde arriba del login.
                    if (!(modelo.getElementAt(pos).getClass().equals("java.lang.String"))) {
                        if (pos == 0) {
                            JOptionPane.showMessageDialog(this, "Selecciona una Categoria", "Error", JOptionPane.ERROR_MESSAGE);
                            listaCategoria.requestFocus();
                        } else {
                            Categoria c = (Categoria) modelo.getElementAt(pos);
                            fecha = pedirFecha(txtFecha.getText());
                            if (fecha.comprobarFecha(txtFecha.getText())) {
                                empresa.anadirNoticia(new Noticia(codigoNot, titulo, c, usuario, fecha));
                                JOptionPane.showMessageDialog(this, "Noticia añadida", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                                limpiar();
                            } else {
                                txtFecha.requestFocus();
                            }
                        }
                    }
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El codigo debe de ser un numero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btAceptarActionPerformed

    private void codNoticKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codNoticKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtTitulo.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            codNotic.setText("");
        }
    }//GEN-LAST:event_codNoticKeyPressed

    private void txtTituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            listaCategoria.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            txtTitulo.setText("");
        }
    }//GEN-LAST:event_txtTituloKeyPressed

    private void listaCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaCategoriaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtFecha.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            listaCategoria.setSelectedIndex(0);
        }
    }//GEN-LAST:event_listaCategoriaKeyPressed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btAceptar.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            txtFecha.setText("");
        }
    }//GEN-LAST:event_txtFechaKeyPressed

    public Fecha pedirFecha(String mensaje) {
        Fecha miFecha = new Fecha();
        if (!(miFecha.comprobarFecha(mensaje))) {
            JOptionPane.showMessageDialog(this, "Fecha incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            txtFecha.setText("");
        }
        return miFecha;
    }

    private void limpiar() {
        codNotic.setText("");
        txtTitulo.setText("");
        listaCategoria.setSelectedIndex(0);
        txtFecha.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JTextField codNotic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> listaCategoria;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
